spring.application.name=backend
python.api.url=http://localhost:8000

# H2 Console Ayarları
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Veritabanı Bağlantı Ayarları (SABİTLEME)
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Hibernate Ayarları (Tabloların otomatik oluşması ve SQL logları için)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect